//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""World"",
            ""id"": ""333d6583-af7b-4463-bb89-dc12b7cdb113"",
            ""actions"": [
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""baed4c61-a25a-48d5-9229-2e85db2aa572"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseDelta"",
                    ""type"": ""Value"",
                    ""id"": ""a58ac3f4-56d5-400d-b22d-ad57fe463cc9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveCamera"",
                    ""type"": ""Value"",
                    ""id"": ""9edbcbaa-872b-49b3-8825-d02ca337afa4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DragCamera"",
                    ""type"": ""Button"",
                    ""id"": ""7ed4e6b1-7839-4a1e-ab98-968cfd4e3099"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateCamera"",
                    ""type"": ""Button"",
                    ""id"": ""0a85a7f5-8298-4586-9582-e82604368b0b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""bb0e4603-0de6-42ce-ba19-eaf2b5787807"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""9d2993b3-caac-4f6e-8ca8-8b784359a708"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""56ab4e61-b5a9-40d5-9004-97d5ba5ca6c7"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""a2a35609-70b1-430a-a1e3-a0f264287da5"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c6ed99f4-a18c-4add-857f-63d58557685b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c64bb0b5-5e92-4704-a4af-c58abb6d42ee"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""be40560c-6a17-4545-ba54-4471620ffc42"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""bf5789aa-eb84-427b-9132-e912e160428a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""ArrowKeys"",
                    ""id"": ""370e04e2-d978-45de-aa8c-b0cafc1f37d2"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""3914d097-09dc-4439-a6d9-6fcaa5ecc208"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d4e286cf-ed9b-4e06-afa3-bb452cfc09b8"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9f0cc468-d053-4821-bd06-19c477abf1d3"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7d409d26-d8a7-48a5-8d10-f952cbf8861e"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a43dc905-ec2a-4ded-9665-5fc1350a275d"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d72546c-6a14-444f-adc3-8b626933c906"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6fc50849-8784-435c-9a0d-b73cc5ba7fd8"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""deccd75d-f5fc-4f59-8420-48591e6d9f6e"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""MouseDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ee9ef05-1559-4d7b-8484-e9fb8b2fc9d0"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""DragCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Inventory"",
            ""id"": ""8dde6780-e02e-4062-a266-3e0686d2a002"",
            ""actions"": [
                {
                    ""name"": ""CloseInventory"",
                    ""type"": ""Button"",
                    ""id"": ""da773435-6846-4ed8-80e5-f9b8415966f6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenBuildMenu"",
                    ""type"": ""Button"",
                    ""id"": ""b18c594a-eb85-4f8b-9eb5-7fce37bc74ab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7425b8c1-cd34-4701-9702-7ce8e8ab7b39"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""CloseInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df104299-a0fd-45f2-96d1-9b1bbc9d518a"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""CloseInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9da20f26-8402-409d-8b99-615ec59a1350"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""OpenBuildMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Build"",
            ""id"": ""e1054432-fc96-4adc-90c2-a02c236d23ad"",
            ""actions"": [
                {
                    ""name"": ""RotateBuilding"",
                    ""type"": ""Value"",
                    ""id"": ""240fca0e-9abb-40ba-9db0-3a5d316839ff"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CloseBuildMenu"",
                    ""type"": ""Button"",
                    ""id"": ""7154093c-2ce0-4f7f-831e-88a73304e669"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenInventory"",
                    ""type"": ""Button"",
                    ""id"": ""f2573d91-4d74-48ae-aeb5-53914fb1f639"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""QE"",
                    ""id"": ""5b1603ab-56fa-4469-ad39-5616d89b28b7"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateBuilding"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""c7fd7c82-1e2d-494b-b944-8b548b65763d"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""RotateBuilding"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""174ff64a-9ba8-44bd-83bd-1f4e386850a4"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""RotateBuilding"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""50ca54eb-52d4-4a54-b403-8e84b990b7fc"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""CloseBuildMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ad8889d-b60d-452a-ad7b-b66c83f72545"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""CloseBuildMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""23a489d5-5fcb-4659-8d8c-44bf875a237b"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""OpenInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Home"",
            ""id"": ""cebf6a23-b35c-43ac-913b-4269ea46e868"",
            ""actions"": [
                {
                    ""name"": ""OpenBuildMenu"",
                    ""type"": ""Button"",
                    ""id"": ""249a3345-0b90-4dc5-97e7-bf272e72621b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenInventory"",
                    ""type"": ""Button"",
                    ""id"": ""64692471-2c71-404d-a7ce-de47180ed6c4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c6bfc5e6-c49f-43e2-bf5d-6de971cfeca7"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""OpenBuildMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b7c40f53-6c61-4834-bbda-422f74136069"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""OpenInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Scavenge"",
            ""id"": ""5debe4a9-3f23-4f63-bf74-91675f5ba518"",
            ""actions"": [
                {
                    ""name"": ""OpenUsableInventory"",
                    ""type"": ""Button"",
                    ""id"": ""8cac9631-2fc2-4d9e-8783-640ef0f21b57"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenCharacterStatus"",
                    ""type"": ""Button"",
                    ""id"": ""3ead7c23-d160-4985-928e-e7c8d5733666"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StopLooting"",
                    ""type"": ""Button"",
                    ""id"": ""98d9120b-61a0-4259-aaeb-f9787df597a1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d1baf79f-8729-4e5e-accf-b7688326ea72"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""OpenUsableInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e691646-0734-4133-8a30-d336e35a108d"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""OpenCharacterStatus"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ff4ae18-50aa-4c94-aff5-533cf5dcf7d5"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""StopLooting"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""155820fa-fdc7-444b-9aeb-8bc62ead6db6"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""StopLooting"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Controller"",
            ""bindingGroup"": ""Controller"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Keyboard and Mouse"",
            ""bindingGroup"": ""Keyboard and Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // World
        m_World = asset.FindActionMap("World", throwIfNotFound: true);
        m_World_MousePosition = m_World.FindAction("MousePosition", throwIfNotFound: true);
        m_World_MouseDelta = m_World.FindAction("MouseDelta", throwIfNotFound: true);
        m_World_MoveCamera = m_World.FindAction("MoveCamera", throwIfNotFound: true);
        m_World_DragCamera = m_World.FindAction("DragCamera", throwIfNotFound: true);
        m_World_RotateCamera = m_World.FindAction("RotateCamera", throwIfNotFound: true);
        m_World_Zoom = m_World.FindAction("Zoom", throwIfNotFound: true);
        m_World_Select = m_World.FindAction("Select", throwIfNotFound: true);
        // Inventory
        m_Inventory = asset.FindActionMap("Inventory", throwIfNotFound: true);
        m_Inventory_CloseInventory = m_Inventory.FindAction("CloseInventory", throwIfNotFound: true);
        m_Inventory_OpenBuildMenu = m_Inventory.FindAction("OpenBuildMenu", throwIfNotFound: true);
        // Build
        m_Build = asset.FindActionMap("Build", throwIfNotFound: true);
        m_Build_RotateBuilding = m_Build.FindAction("RotateBuilding", throwIfNotFound: true);
        m_Build_CloseBuildMenu = m_Build.FindAction("CloseBuildMenu", throwIfNotFound: true);
        m_Build_OpenInventory = m_Build.FindAction("OpenInventory", throwIfNotFound: true);
        // Home
        m_Home = asset.FindActionMap("Home", throwIfNotFound: true);
        m_Home_OpenBuildMenu = m_Home.FindAction("OpenBuildMenu", throwIfNotFound: true);
        m_Home_OpenInventory = m_Home.FindAction("OpenInventory", throwIfNotFound: true);
        // Scavenge
        m_Scavenge = asset.FindActionMap("Scavenge", throwIfNotFound: true);
        m_Scavenge_OpenUsableInventory = m_Scavenge.FindAction("OpenUsableInventory", throwIfNotFound: true);
        m_Scavenge_OpenCharacterStatus = m_Scavenge.FindAction("OpenCharacterStatus", throwIfNotFound: true);
        m_Scavenge_StopLooting = m_Scavenge.FindAction("StopLooting", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // World
    private readonly InputActionMap m_World;
    private IWorldActions m_WorldActionsCallbackInterface;
    private readonly InputAction m_World_MousePosition;
    private readonly InputAction m_World_MouseDelta;
    private readonly InputAction m_World_MoveCamera;
    private readonly InputAction m_World_DragCamera;
    private readonly InputAction m_World_RotateCamera;
    private readonly InputAction m_World_Zoom;
    private readonly InputAction m_World_Select;
    public struct WorldActions
    {
        private @PlayerControls m_Wrapper;
        public WorldActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MousePosition => m_Wrapper.m_World_MousePosition;
        public InputAction @MouseDelta => m_Wrapper.m_World_MouseDelta;
        public InputAction @MoveCamera => m_Wrapper.m_World_MoveCamera;
        public InputAction @DragCamera => m_Wrapper.m_World_DragCamera;
        public InputAction @RotateCamera => m_Wrapper.m_World_RotateCamera;
        public InputAction @Zoom => m_Wrapper.m_World_Zoom;
        public InputAction @Select => m_Wrapper.m_World_Select;
        public InputActionMap Get() { return m_Wrapper.m_World; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(WorldActions set) { return set.Get(); }
        public void SetCallbacks(IWorldActions instance)
        {
            if (m_Wrapper.m_WorldActionsCallbackInterface != null)
            {
                @MousePosition.started -= m_Wrapper.m_WorldActionsCallbackInterface.OnMousePosition;
                @MousePosition.performed -= m_Wrapper.m_WorldActionsCallbackInterface.OnMousePosition;
                @MousePosition.canceled -= m_Wrapper.m_WorldActionsCallbackInterface.OnMousePosition;
                @MouseDelta.started -= m_Wrapper.m_WorldActionsCallbackInterface.OnMouseDelta;
                @MouseDelta.performed -= m_Wrapper.m_WorldActionsCallbackInterface.OnMouseDelta;
                @MouseDelta.canceled -= m_Wrapper.m_WorldActionsCallbackInterface.OnMouseDelta;
                @MoveCamera.started -= m_Wrapper.m_WorldActionsCallbackInterface.OnMoveCamera;
                @MoveCamera.performed -= m_Wrapper.m_WorldActionsCallbackInterface.OnMoveCamera;
                @MoveCamera.canceled -= m_Wrapper.m_WorldActionsCallbackInterface.OnMoveCamera;
                @DragCamera.started -= m_Wrapper.m_WorldActionsCallbackInterface.OnDragCamera;
                @DragCamera.performed -= m_Wrapper.m_WorldActionsCallbackInterface.OnDragCamera;
                @DragCamera.canceled -= m_Wrapper.m_WorldActionsCallbackInterface.OnDragCamera;
                @RotateCamera.started -= m_Wrapper.m_WorldActionsCallbackInterface.OnRotateCamera;
                @RotateCamera.performed -= m_Wrapper.m_WorldActionsCallbackInterface.OnRotateCamera;
                @RotateCamera.canceled -= m_Wrapper.m_WorldActionsCallbackInterface.OnRotateCamera;
                @Zoom.started -= m_Wrapper.m_WorldActionsCallbackInterface.OnZoom;
                @Zoom.performed -= m_Wrapper.m_WorldActionsCallbackInterface.OnZoom;
                @Zoom.canceled -= m_Wrapper.m_WorldActionsCallbackInterface.OnZoom;
                @Select.started -= m_Wrapper.m_WorldActionsCallbackInterface.OnSelect;
                @Select.performed -= m_Wrapper.m_WorldActionsCallbackInterface.OnSelect;
                @Select.canceled -= m_Wrapper.m_WorldActionsCallbackInterface.OnSelect;
            }
            m_Wrapper.m_WorldActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MousePosition.started += instance.OnMousePosition;
                @MousePosition.performed += instance.OnMousePosition;
                @MousePosition.canceled += instance.OnMousePosition;
                @MouseDelta.started += instance.OnMouseDelta;
                @MouseDelta.performed += instance.OnMouseDelta;
                @MouseDelta.canceled += instance.OnMouseDelta;
                @MoveCamera.started += instance.OnMoveCamera;
                @MoveCamera.performed += instance.OnMoveCamera;
                @MoveCamera.canceled += instance.OnMoveCamera;
                @DragCamera.started += instance.OnDragCamera;
                @DragCamera.performed += instance.OnDragCamera;
                @DragCamera.canceled += instance.OnDragCamera;
                @RotateCamera.started += instance.OnRotateCamera;
                @RotateCamera.performed += instance.OnRotateCamera;
                @RotateCamera.canceled += instance.OnRotateCamera;
                @Zoom.started += instance.OnZoom;
                @Zoom.performed += instance.OnZoom;
                @Zoom.canceled += instance.OnZoom;
                @Select.started += instance.OnSelect;
                @Select.performed += instance.OnSelect;
                @Select.canceled += instance.OnSelect;
            }
        }
    }
    public WorldActions @World => new WorldActions(this);

    // Inventory
    private readonly InputActionMap m_Inventory;
    private IInventoryActions m_InventoryActionsCallbackInterface;
    private readonly InputAction m_Inventory_CloseInventory;
    private readonly InputAction m_Inventory_OpenBuildMenu;
    public struct InventoryActions
    {
        private @PlayerControls m_Wrapper;
        public InventoryActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @CloseInventory => m_Wrapper.m_Inventory_CloseInventory;
        public InputAction @OpenBuildMenu => m_Wrapper.m_Inventory_OpenBuildMenu;
        public InputActionMap Get() { return m_Wrapper.m_Inventory; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InventoryActions set) { return set.Get(); }
        public void SetCallbacks(IInventoryActions instance)
        {
            if (m_Wrapper.m_InventoryActionsCallbackInterface != null)
            {
                @CloseInventory.started -= m_Wrapper.m_InventoryActionsCallbackInterface.OnCloseInventory;
                @CloseInventory.performed -= m_Wrapper.m_InventoryActionsCallbackInterface.OnCloseInventory;
                @CloseInventory.canceled -= m_Wrapper.m_InventoryActionsCallbackInterface.OnCloseInventory;
                @OpenBuildMenu.started -= m_Wrapper.m_InventoryActionsCallbackInterface.OnOpenBuildMenu;
                @OpenBuildMenu.performed -= m_Wrapper.m_InventoryActionsCallbackInterface.OnOpenBuildMenu;
                @OpenBuildMenu.canceled -= m_Wrapper.m_InventoryActionsCallbackInterface.OnOpenBuildMenu;
            }
            m_Wrapper.m_InventoryActionsCallbackInterface = instance;
            if (instance != null)
            {
                @CloseInventory.started += instance.OnCloseInventory;
                @CloseInventory.performed += instance.OnCloseInventory;
                @CloseInventory.canceled += instance.OnCloseInventory;
                @OpenBuildMenu.started += instance.OnOpenBuildMenu;
                @OpenBuildMenu.performed += instance.OnOpenBuildMenu;
                @OpenBuildMenu.canceled += instance.OnOpenBuildMenu;
            }
        }
    }
    public InventoryActions @Inventory => new InventoryActions(this);

    // Build
    private readonly InputActionMap m_Build;
    private IBuildActions m_BuildActionsCallbackInterface;
    private readonly InputAction m_Build_RotateBuilding;
    private readonly InputAction m_Build_CloseBuildMenu;
    private readonly InputAction m_Build_OpenInventory;
    public struct BuildActions
    {
        private @PlayerControls m_Wrapper;
        public BuildActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @RotateBuilding => m_Wrapper.m_Build_RotateBuilding;
        public InputAction @CloseBuildMenu => m_Wrapper.m_Build_CloseBuildMenu;
        public InputAction @OpenInventory => m_Wrapper.m_Build_OpenInventory;
        public InputActionMap Get() { return m_Wrapper.m_Build; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BuildActions set) { return set.Get(); }
        public void SetCallbacks(IBuildActions instance)
        {
            if (m_Wrapper.m_BuildActionsCallbackInterface != null)
            {
                @RotateBuilding.started -= m_Wrapper.m_BuildActionsCallbackInterface.OnRotateBuilding;
                @RotateBuilding.performed -= m_Wrapper.m_BuildActionsCallbackInterface.OnRotateBuilding;
                @RotateBuilding.canceled -= m_Wrapper.m_BuildActionsCallbackInterface.OnRotateBuilding;
                @CloseBuildMenu.started -= m_Wrapper.m_BuildActionsCallbackInterface.OnCloseBuildMenu;
                @CloseBuildMenu.performed -= m_Wrapper.m_BuildActionsCallbackInterface.OnCloseBuildMenu;
                @CloseBuildMenu.canceled -= m_Wrapper.m_BuildActionsCallbackInterface.OnCloseBuildMenu;
                @OpenInventory.started -= m_Wrapper.m_BuildActionsCallbackInterface.OnOpenInventory;
                @OpenInventory.performed -= m_Wrapper.m_BuildActionsCallbackInterface.OnOpenInventory;
                @OpenInventory.canceled -= m_Wrapper.m_BuildActionsCallbackInterface.OnOpenInventory;
            }
            m_Wrapper.m_BuildActionsCallbackInterface = instance;
            if (instance != null)
            {
                @RotateBuilding.started += instance.OnRotateBuilding;
                @RotateBuilding.performed += instance.OnRotateBuilding;
                @RotateBuilding.canceled += instance.OnRotateBuilding;
                @CloseBuildMenu.started += instance.OnCloseBuildMenu;
                @CloseBuildMenu.performed += instance.OnCloseBuildMenu;
                @CloseBuildMenu.canceled += instance.OnCloseBuildMenu;
                @OpenInventory.started += instance.OnOpenInventory;
                @OpenInventory.performed += instance.OnOpenInventory;
                @OpenInventory.canceled += instance.OnOpenInventory;
            }
        }
    }
    public BuildActions @Build => new BuildActions(this);

    // Home
    private readonly InputActionMap m_Home;
    private IHomeActions m_HomeActionsCallbackInterface;
    private readonly InputAction m_Home_OpenBuildMenu;
    private readonly InputAction m_Home_OpenInventory;
    public struct HomeActions
    {
        private @PlayerControls m_Wrapper;
        public HomeActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @OpenBuildMenu => m_Wrapper.m_Home_OpenBuildMenu;
        public InputAction @OpenInventory => m_Wrapper.m_Home_OpenInventory;
        public InputActionMap Get() { return m_Wrapper.m_Home; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(HomeActions set) { return set.Get(); }
        public void SetCallbacks(IHomeActions instance)
        {
            if (m_Wrapper.m_HomeActionsCallbackInterface != null)
            {
                @OpenBuildMenu.started -= m_Wrapper.m_HomeActionsCallbackInterface.OnOpenBuildMenu;
                @OpenBuildMenu.performed -= m_Wrapper.m_HomeActionsCallbackInterface.OnOpenBuildMenu;
                @OpenBuildMenu.canceled -= m_Wrapper.m_HomeActionsCallbackInterface.OnOpenBuildMenu;
                @OpenInventory.started -= m_Wrapper.m_HomeActionsCallbackInterface.OnOpenInventory;
                @OpenInventory.performed -= m_Wrapper.m_HomeActionsCallbackInterface.OnOpenInventory;
                @OpenInventory.canceled -= m_Wrapper.m_HomeActionsCallbackInterface.OnOpenInventory;
            }
            m_Wrapper.m_HomeActionsCallbackInterface = instance;
            if (instance != null)
            {
                @OpenBuildMenu.started += instance.OnOpenBuildMenu;
                @OpenBuildMenu.performed += instance.OnOpenBuildMenu;
                @OpenBuildMenu.canceled += instance.OnOpenBuildMenu;
                @OpenInventory.started += instance.OnOpenInventory;
                @OpenInventory.performed += instance.OnOpenInventory;
                @OpenInventory.canceled += instance.OnOpenInventory;
            }
        }
    }
    public HomeActions @Home => new HomeActions(this);

    // Scavenge
    private readonly InputActionMap m_Scavenge;
    private IScavengeActions m_ScavengeActionsCallbackInterface;
    private readonly InputAction m_Scavenge_OpenUsableInventory;
    private readonly InputAction m_Scavenge_OpenCharacterStatus;
    private readonly InputAction m_Scavenge_StopLooting;
    public struct ScavengeActions
    {
        private @PlayerControls m_Wrapper;
        public ScavengeActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @OpenUsableInventory => m_Wrapper.m_Scavenge_OpenUsableInventory;
        public InputAction @OpenCharacterStatus => m_Wrapper.m_Scavenge_OpenCharacterStatus;
        public InputAction @StopLooting => m_Wrapper.m_Scavenge_StopLooting;
        public InputActionMap Get() { return m_Wrapper.m_Scavenge; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ScavengeActions set) { return set.Get(); }
        public void SetCallbacks(IScavengeActions instance)
        {
            if (m_Wrapper.m_ScavengeActionsCallbackInterface != null)
            {
                @OpenUsableInventory.started -= m_Wrapper.m_ScavengeActionsCallbackInterface.OnOpenUsableInventory;
                @OpenUsableInventory.performed -= m_Wrapper.m_ScavengeActionsCallbackInterface.OnOpenUsableInventory;
                @OpenUsableInventory.canceled -= m_Wrapper.m_ScavengeActionsCallbackInterface.OnOpenUsableInventory;
                @OpenCharacterStatus.started -= m_Wrapper.m_ScavengeActionsCallbackInterface.OnOpenCharacterStatus;
                @OpenCharacterStatus.performed -= m_Wrapper.m_ScavengeActionsCallbackInterface.OnOpenCharacterStatus;
                @OpenCharacterStatus.canceled -= m_Wrapper.m_ScavengeActionsCallbackInterface.OnOpenCharacterStatus;
                @StopLooting.started -= m_Wrapper.m_ScavengeActionsCallbackInterface.OnStopLooting;
                @StopLooting.performed -= m_Wrapper.m_ScavengeActionsCallbackInterface.OnStopLooting;
                @StopLooting.canceled -= m_Wrapper.m_ScavengeActionsCallbackInterface.OnStopLooting;
            }
            m_Wrapper.m_ScavengeActionsCallbackInterface = instance;
            if (instance != null)
            {
                @OpenUsableInventory.started += instance.OnOpenUsableInventory;
                @OpenUsableInventory.performed += instance.OnOpenUsableInventory;
                @OpenUsableInventory.canceled += instance.OnOpenUsableInventory;
                @OpenCharacterStatus.started += instance.OnOpenCharacterStatus;
                @OpenCharacterStatus.performed += instance.OnOpenCharacterStatus;
                @OpenCharacterStatus.canceled += instance.OnOpenCharacterStatus;
                @StopLooting.started += instance.OnStopLooting;
                @StopLooting.performed += instance.OnStopLooting;
                @StopLooting.canceled += instance.OnStopLooting;
            }
        }
    }
    public ScavengeActions @Scavenge => new ScavengeActions(this);
    private int m_ControllerSchemeIndex = -1;
    public InputControlScheme ControllerScheme
    {
        get
        {
            if (m_ControllerSchemeIndex == -1) m_ControllerSchemeIndex = asset.FindControlSchemeIndex("Controller");
            return asset.controlSchemes[m_ControllerSchemeIndex];
        }
    }
    private int m_KeyboardandMouseSchemeIndex = -1;
    public InputControlScheme KeyboardandMouseScheme
    {
        get
        {
            if (m_KeyboardandMouseSchemeIndex == -1) m_KeyboardandMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard and Mouse");
            return asset.controlSchemes[m_KeyboardandMouseSchemeIndex];
        }
    }
    public interface IWorldActions
    {
        void OnMousePosition(InputAction.CallbackContext context);
        void OnMouseDelta(InputAction.CallbackContext context);
        void OnMoveCamera(InputAction.CallbackContext context);
        void OnDragCamera(InputAction.CallbackContext context);
        void OnRotateCamera(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
    }
    public interface IInventoryActions
    {
        void OnCloseInventory(InputAction.CallbackContext context);
        void OnOpenBuildMenu(InputAction.CallbackContext context);
    }
    public interface IBuildActions
    {
        void OnRotateBuilding(InputAction.CallbackContext context);
        void OnCloseBuildMenu(InputAction.CallbackContext context);
        void OnOpenInventory(InputAction.CallbackContext context);
    }
    public interface IHomeActions
    {
        void OnOpenBuildMenu(InputAction.CallbackContext context);
        void OnOpenInventory(InputAction.CallbackContext context);
    }
    public interface IScavengeActions
    {
        void OnOpenUsableInventory(InputAction.CallbackContext context);
        void OnOpenCharacterStatus(InputAction.CallbackContext context);
        void OnStopLooting(InputAction.CallbackContext context);
    }
}
